### ISSUE TITLE
Better compatibility with JAOPCA

### ISSUE THREAD

**Issue by DMNerd** [gisellevonbingen-Minecraft/MoreMekanismProcessing#37]
Hello! I would like to know wheter a compatibility patch with JAOPCA could be made that automatically disables the overlaping items? I love the JAOPCA module you have in the Beyond Earth addon and I think that a Extensive support for it in this mod would be a godsend

Thank you for your work :)

**Comment by gisellevonbingen** [comment]
I've tried various things instead,
I don't have the skills to dynamically register items well.
Incompatible with JAOPCA right now.

So sorry, Thanks for your great interest.
