### ISSUE TITLE
Please add Advent of Ascension integration

### ISSUE THREAD

**Issue by MagnusMedivh** [gisellevonbingen-Minecraft/MoreMekanismProcessing#38]
It would be awesome if you added integration with ores from Advent of Ascension mod, at least for 1.16.5

https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine

**Comment by gisellevonbingen** [comment]
It doesn't seem to be a common ore used in other mods.

It seems that the 'Advent of Ascension' developers are very interested in compatibility.
Would you check to 'Advent of Ascension' developers first whether will they add mekanism compatibility?
